// Code generated by github.com/zostay/go-esv-api/tools/gen
// DO NOT EDIT!!!

package esv

const (
	// DefaultBaseURL is the base URL of the ESV API site online.
	DefaultBaseURL = "https://api.esv.org/v3/"
)

// WithIncludePassageReferences provides the "include-passage-references" option to pass with your API
// call to ESV API.
func WithIncludePassageReferences(o bool) optionBool {
	return optionBool{"include-passage-references", o}
}

// WithIncludeVerseNumbers provides the "include-verse-numbers" option to pass with your API
// call to ESV API.
func WithIncludeVerseNumbers(o bool) optionBool {
	return optionBool{"include-verse-numbers", o}
}

// WithIncludeFirstVerseNumbers provides the "include-first-verse-numbers" option to pass with your API
// call to ESV API.
func WithIncludeFirstVerseNumbers(o bool) optionBool {
	return optionBool{"include-first-verse-numbers", o}
}

// WithIncludeFootnotes provides the "include-footnotes" option to pass with your API
// call to ESV API.
func WithIncludeFootnotes(o bool) optionBool {
	return optionBool{"include-footnotes", o}
}

// WithIncludeFootnoteBody provides the "include-footnote-body" option to pass with your API
// call to ESV API.
func WithIncludeFootnoteBody(o bool) optionBool {
	return optionBool{"include-footnote-body", o}
}

// WithIncludeHeadings provides the "include-headings" option to pass with your API
// call to ESV API.
func WithIncludeHeadings(o bool) optionBool {
	return optionBool{"include-headings", o}
}

// WithIncludeShortCopyright provides the "include-short-copyright" option to pass with your API
// call to ESV API.
func WithIncludeShortCopyright(o bool) optionBool {
	return optionBool{"include-short-copyright", o}
}

// WithIncludeCopyright provides the "include-copyright" option to pass with your API
// call to ESV API.
func WithIncludeCopyright(o bool) optionBool {
	return optionBool{"include-copyright", o}
}

// WithIncludePassageHorizontalLines provides the "include-passage-horizontal-lines" option to pass with your API
// call to ESV API.
func WithIncludePassageHorizontalLines(o bool) optionBool {
	return optionBool{"include-passage-horizontal-lines", o}
}

// WithIncludeHeadingHorizontalLines provides the "include-heading-horizontal-lines" option to pass with your API
// call to ESV API.
func WithIncludeHeadingHorizontalLines(o bool) optionBool {
	return optionBool{"include-heading-horizontal-lines", o}
}

// WithHorizontalLineLength provides the "horizontal-line-length" option to pass with your API
// call to ESV API.
func WithHorizontalLineLength(o int) optionInt {
	return optionInt{"horizontal-line-length", o}
}

// WithIncludeSelahs provides the "include-selahs" option to pass with your API
// call to ESV API.
func WithIncludeSelahs(o bool) optionBool {
	return optionBool{"include-selahs", o}
}

// WithIndentUsing provides the "indent-using" option to pass with your API
// call to ESV API.
func WithIndentUsing(o string) optionString {
	return optionString{"indent-using", o}
}

// WithIndentParagraphs provides the "indent-paragraphs" option to pass with your API
// call to ESV API.
func WithIndentParagraphs(o int) optionInt {
	return optionInt{"indent-paragraphs", o}
}

// WithIndentPoetry provides the "indent-poetry" option to pass with your API
// call to ESV API.
func WithIndentPoetry(o bool) optionBool {
	return optionBool{"indent-poetry", o}
}

// WithIndentPoetryLines provides the "indent-poetry-lines" option to pass with your API
// call to ESV API.
func WithIndentPoetryLines(o int) optionInt {
	return optionInt{"indent-poetry-lines", o}
}

// WithIndentDeclares provides the "indent-declares" option to pass with your API
// call to ESV API.
func WithIndentDeclares(o int) optionInt {
	return optionInt{"indent-declares", o}
}

// WithIndentPsalmDoxology provides the "indent-psalm-doxology" option to pass with your API
// call to ESV API.
func WithIndentPsalmDoxology(o int) optionInt {
	return optionInt{"indent-psalm-doxology", o}
}

// WithLineLength provides the "line-length" option to pass with your API
// call to ESV API.
func WithLineLength(o int) optionInt {
	return optionInt{"line-length", o}
}

// PassageTextResult is the structure returned by PassageText
// containing the response to your request.
type PassageTextResult struct {
	Query       string
	Canonical   string
	Parsed      [][]Location
	PassageMeta struct {
		Canonical    string
		ChapterStart []Location
		ChapterEnd   []Location
		PrevVerse    Location
		NextVerse    Location
		PrevChapter  []Location
		NextChapter  []Location
	}
	Passages []string
}

// PassageText performs the "passage/text" ESV API call and returns
// PassageText with your results.
func (c Client) PassageText(q string, o ...Option) (PassageTextResult, error) {
	opts := make([]Option, len(o)+1)

	opts[0] = optionString{"q", q}

	for i, opt := range o {
		opts[i+1] = opt
	}
	var result PassageTextResult
	err := c.CallEndpoint("passage/text", opts, &result)
	return result, err
}

// WithIncludeCssLink provides the "include-css-link" option to pass with your API
// call to ESV API.
func WithIncludeCssLink(o bool) optionBool {
	return optionBool{"include-css-link", o}
}

// WithInlineStyles provides the "inline-styles" option to pass with your API
// call to ESV API.
func WithInlineStyles(o bool) optionBool {
	return optionBool{"inline-styles", o}
}

// WithWrappingDiv provides the "wrapping-div" option to pass with your API
// call to ESV API.
func WithWrappingDiv(o bool) optionBool {
	return optionBool{"wrapping-div", o}
}

// WithDivClasses provides the "div-classes" option to pass with your API
// call to ESV API.
func WithDivClasses(o string) optionString {
	return optionString{"div-classes", o}
}

// WithParagraphTag provides the "paragraph-tag" option to pass with your API
// call to ESV API.
func WithParagraphTag(o string) optionString {
	return optionString{"paragraph-tag", o}
}

// WithIncludeBookTitles provides the "include-book-titles" option to pass with your API
// call to ESV API.
func WithIncludeBookTitles(o bool) optionBool {
	return optionBool{"include-book-titles", o}
}

// WithIncludeVerseAnchors provides the "include-verse-anchors" option to pass with your API
// call to ESV API.
func WithIncludeVerseAnchors(o bool) optionBool {
	return optionBool{"include-verse-anchors", o}
}

// WithIncludeChapterNumbers provides the "include-chapter-numbers" option to pass with your API
// call to ESV API.
func WithIncludeChapterNumbers(o bool) optionBool {
	return optionBool{"include-chapter-numbers", o}
}

// WithIncludeCrossrefs provides the "include-crossrefs" option to pass with your API
// call to ESV API.
func WithIncludeCrossrefs(o bool) optionBool {
	return optionBool{"include-crossrefs", o}
}

// WithIncludeSubheadings provides the "include-subheadings" option to pass with your API
// call to ESV API.
func WithIncludeSubheadings(o bool) optionBool {
	return optionBool{"include-subheadings", o}
}

// WithIncludeSurroundingChapters provides the "include-surrounding-chapters" option to pass with your API
// call to ESV API.
func WithIncludeSurroundingChapters(o bool) optionBool {
	return optionBool{"include-surrounding-chapters", o}
}

// WithIncludeSurroundingChaptersBelow provides the "include-surrounding-chapters-below" option to pass with your API
// call to ESV API.
func WithIncludeSurroundingChaptersBelow(o string) optionString {
	return optionString{"include-surrounding-chapters-below", o}
}

// WithIncludeSurroundingChaptersBelowThreshold provides the "include-surrounding-chapters-below-threshold" option to pass with your API
// call to ESV API.
func WithIncludeSurroundingChaptersBelowThreshold(o int) optionInt {
	return optionInt{"include-surrounding-chapters-below-threshold", o}
}

// WithLinkUrl provides the "link-url" option to pass with your API
// call to ESV API.
func WithLinkUrl(o string) optionString {
	return optionString{"link-url", o}
}

// WithCrossrefUrl provides the "crossref-url" option to pass with your API
// call to ESV API.
func WithCrossrefUrl(o string) optionString {
	return optionString{"crossref-url", o}
}

// WithPrefaceUrl provides the "preface-url" option to pass with your API
// call to ESV API.
func WithPrefaceUrl(o string) optionString {
	return optionString{"preface-url", o}
}

// WithIncludeAudioLink provides the "include-audio-link" option to pass with your API
// call to ESV API.
func WithIncludeAudioLink(o bool) optionBool {
	return optionBool{"include-audio-link", o}
}

// WithAttachAudioLinkTo provides the "attach-audio-link-to" option to pass with your API
// call to ESV API.
func WithAttachAudioLinkTo(o string) optionString {
	return optionString{"attach-audio-link-to", o}
}

// PassageHtmlResult is the structure returned by PassageHtml
// containing the response to your request.
type PassageHtmlResult struct {
	Query       string
	Canonical   string
	Parsed      [][]Location
	PassageMeta struct {
		Canonical    string
		ChapterStart []Location
		ChapterEnd   []Location
		PrevVerse    Location
		NextVerse    Location
		PrevChapter  []Location
		NextChapter  []Location
	}
	Passages []string
}

// PassageHtml performs the "passage/html" ESV API call and returns
// PassageHtml with your results.
func (c Client) PassageHtml(q string, o ...Option) (PassageHtmlResult, error) {
	opts := make([]Option, len(o)+1)

	opts[0] = optionString{"q", q}

	for i, opt := range o {
		opts[i+1] = opt
	}
	var result PassageHtmlResult
	err := c.CallEndpoint("passage/html", opts, &result)
	return result, err
}

// WithPageSize provides the "page-size" option to pass with your API
// call to ESV API.
func WithPageSize(o int) optionInt {
	return optionInt{"page-size", o}
}

// WithPage provides the "page" option to pass with your API
// call to ESV API.
func WithPage(o int) optionInt {
	return optionInt{"page", o}
}

// PassageSearchResult is the structure returned by PassageSearch
// containing the response to your request.
type PassageSearchResult struct {
	Page         int
	TotalResults int
	Results      []struct {
		Reference string
		Content   string
	}
	TotalPages int
}

// PassageSearch performs the "passage/search" ESV API call and returns
// PassageSearch with your results.
func (c Client) PassageSearch(q string, o ...Option) (PassageSearchResult, error) {
	opts := make([]Option, len(o)+1)

	opts[0] = optionString{"q", q}

	for i, opt := range o {
		opts[i+1] = opt
	}
	var result PassageSearchResult
	err := c.CallEndpoint("passage/search", opts, &result)
	return result, err
}
